### ISSUE TITLE
Depends on AFNetworking 2.x

### ISSUE THREAD

**Issue by adamsp** [seatgeek/SGHTTPRequest#1]
Your [Podspec](https://github.com/CocoaPods/Specs/blob/master/Specs/SGHTTPRequest/1.1.0/SGHTTPRequest.podspec.json) doesn't specify a version of AFNetworking. I use RestKit in my project, which depends on AFNetworking 1.3. Unfortunately, SGHTTPRequest depends on some AFNetworking classes introduced in 2.0.

Since no minimum version is specified in your Podspec, Cocoapods was happy to install alongside (this came down as a dependency of [SGImageCache](https://github.com/seatgeek/SGImageCache)), but of course this didn't work out so well at compile time.

I'm not sure if this is the right place to report this (or if this is even an issue that should be resolved at your level), as I'm fairly new to the Cocoapods system (and iOS development in general).

Thanks!

**Comment by sobri909** [comment]
Good point. This needs to be explicit.

Yep, this is the right place to report it! We'll fix. Thanks :)

**Comment by staminajim** [comment]
Thanks @adamsp , I've updated the pod spec.

**Comment by adamsp** [comment]
:tada:
